name: Label issues with "common" label.

on:
  issues:
    types: opened

permissions:
  issues: write

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: add label
        id: add_label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: common
