name: Transfer issues to container-libs.

on:
  issues:
    types: opened

permissions:
  issues: write

jobs:
  add_label:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: common

      - name: transfer issuea
        uses: lando/transfer-issue-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          router: common:container-libs
