on:
  issues:
    types: [opened]

jobs:
  auto_close_issues:
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v3
        with:
          comment: |
            This repository has been migrated to https://github.com/containers/container-libs. Please open your issue there.
