name: Transfer issues to container-libs.

on:
  issues:
    types: labeled

permissions:
  issues: write

jobs:
  transfer_issue:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: transfer issue
        uses: lando/transfer-issue-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          router: common:container-libs
