---
name: Image - Codespell

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  image-codespell:
    name: Check for spelling errors
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./image

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Copy .codespellrc
        run: cp ./image/.codespellrc ./.codespellrc
      - name: Codespell
        # uses configuration within .codespellrc file
        uses: codespell-project/actions-codespell@v2
        with:
          path: ./image
